engine:
    type: HighThroughputEngine
    max_workers_per_node: 1
    worker_debug: False

    address:
        type: address_by_interface
        ifname: ib0

    provider:
        type: SlurmProvider
        partition: {{ PARTITION }}  # e.g., bdws
        launcher:
          type: SrunLauncher

        # string to prepend to #SBATCH blocks in the submit
        # script to the scheduler
        # eg: '#SBATCH --constraint=knl,quad,cache'
        scheduler_options: {{ OPTIONS }}

        # Command to be run before starting a worker
        # e.g., "module load Anaconda; source activate parsl_env"
        worker_init: {{ COMMAND }}

        nodes_per_block: 1
        init_blocks: 1
        min_blocks: 0
        max_blocks: 1
        walltime: 00:30:00
