engine:
    type: HighThroughputEngine
    max_workers_per_node: 1
    worker_debug: False
    address: 127.0.0.1

    provider:
        type: TorqueProvider
        queue: normal

        launcher:
            type: AprunLauncher
            overrides: -b -- bwpy-environ --

        # string to prepend to #SBATCH blocks in the submit
        scheduler_options: {{ OPTIONS }}

        # Command to be run before starting a worker
        # e.g., "module load bwpy; source activate compute env"
        worker_init: {{ COMMAND }}

        # Scale between 0-1 blocks with 2 nodes per block
        nodes_per_block: 2
        init_blocks: 0
        min_blocks: 0
        max_blocks: 1

        # Hold blocks for 30 minutes
        walltime: 00:30:00
