display_name: Stampede2.TACC.batch

engine:
  type: HighThroughputEngine
  address:
    type: address_by_interface
    ifname: em3

  max_workers_per_node: 2

  provider:
    type: SlurmProvider
    partition: development

    launcher:
        type: SrunLauncher

    # string to prepend to #SBATCH blocks in the submit
    # script to the scheduler
    # e.g., "#SBATCH --constraint=knl,quad,cache"
    scheduler_options: {{ OPTIONS }}

    # Command to be run before starting a worker
    # e.g., module load Anaconda; source activate parsl_env
    # e.g., "source ~/anaconda3/bin/activate; conda activate gce_py3.9"
    worker_init: {{ COMMAND }}

    # Scale between 0-1 blocks with 2 nodes per block
    nodes_per_block: 2
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0

    # Blocks are provisioned for a maxmimum of 10 minutes
    walltime: 00:10:00
