heartbeat_period: 15
heartbeat_threshold: 200

engine:
    type: GlobusComputeEngine
    max_workers_per_node: 1

    # Encryption is not currently supported for KubernetesProvider
    encrypted: false

    address:
      type: address_by_route

    provider:
        type: KubernetesProvider
        init_blocks: 0
        min_blocks: 0
        max_blocks: 2
        init_cpu: 1
        max_cpu: 4
        init_mem: 1024Mi
        max_mem: 4096Mi

        # e.g., default
        namespace: {{ NAMESPACE }}

        # Must follow Kubernetes naming rules
        # e.g., globus-compute-pod
        pod_name: {{ POD_NAME }}

        # e.g., python:3.12-bookworm
        image: {{ IMAGE }}

        # The secret key to download the image
        secret: {{ SECRET }}

        # e.g., "pip install --force-reinstall globus-compute-endpoint"
        worker_init: {{ COMMAND }}