heartbeat_period: 15
heartbeat_threshold: 200
log_dir: "."

engine:
    type: HighThroughputEngine
    label: Kubernetes_funcX
    max_workers_per_node: 1

    address:
      type: address_by_route

    scheduler_mode: hard
    container_type: docker

    strategy:
        type: KubeSimpleStrategy
        max_idletime: 3600

    provider:
        type: KubernetesProvider
        init_blocks: 0
        min_blocks: 0
        max_blocks: 2
        init_cpu: 1
        max_cpu: 4
        init_mem: 1024Mi
        max_mem: 4096Mi

        # e.g., python:3.8-buster
        image: {{ IMAGE }}

        # e.g., "pip install --force-reinstall globus_compute_endpoint>=2.0.1"
        worker_init: {{ COMMAND }}

        # e.g., default
        namespace: {{ NAMESPACE }}

        incluster_config: False

