apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-endpoint-instance-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  config.py: |
    from funcx_endpoint.endpoint.utils.config import Config
    from funcx_endpoint.providers.kubernetes.kube import KubernetesProvider
    from funcx_endpoint.strategies import KubeSimpleStrategy

    config = Config(
        scaling_enabled=True,
        provider=KubernetesProvider(
            init_blocks=0,
            min_blocks=1,
            max_blocks=1,
            image="{{ .Values.workerImage }}",
            worker_init='{{ .Values.workerInit }}',
            namespace='{{ .Values.workerNamespace }}'
        ),
        strategy=KubeSimpleStrategy(max_idletime=3600),
        scheduler_mode='hard',
        heartbeat_period=15,
        heartbeat_threshold=200,
        max_workers_per_node=1,
        working_dir='/tmp/worker_logs',
        funcx_service_address="{{ .Values.funcXServiceAddress }}/v1"
    )

    # For now, visible_to must be a list of URNs for globus auth users or groups, e.g.:
    # urn:globus:auth:identity:{user_uuid}
    # urn:globus:groups:id:{group_uuid}
    meta = {
    "name": "default",
    "description": "",
    "organization": "",
    "department": "",
    "public": True,
    "visible_to": []
    }
