name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  test-endpoint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
        # needed because the rabbitmq container does not provide a healthcheck
        options: --health-cmd "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_virtual_hosts && rabbitmq-diagnostics -q check_port_connectivity" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    name: "Test Endpoint on py${{ matrix.python-version }} x ${{ matrix.os }} "
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip setuptools
      - run: python -m pip install tox
      - name: run tests
        run: |
          cd compute_endpoint
          tox -e py -- --log-cli-level=ERROR
      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.2
