name: hourly

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: "manual test"

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install -U pip setuptools
    - run: python -m pip install tox
    - name: Run smoke tests to check liveness of hosted services
      env:
        FUNCX_SMOKE_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
        FUNCX_SMOKE_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
      run: |
        cd smoke_tests
        make prod

  notify:
    runs-on: ubuntu-latest
    needs: [smoke-test]
    if: failure()
    steps:
      # FIXME: make this send to a listhost or Slack
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.repository }} - Hourly smoke test failed
          to: ryan.chard@gmail.com,rchard@anl.gov,chard@uchicago.edu,yadudoc1729@gmail.com,josh@globus.org,bengal1@illinois.edu,benc@hawaga.org.uk,sirosen@globus.org
          from: funcX Tests # <user@example.com>
          body: The hourly ${{ github.repository }} workflow failed!
