name: hourly

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: "manual test"

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies for funcx-sdk and test requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install './funcx_sdk[test]'
        # fixme: Remove this next install line once issue #640 is fixed.
        python -m pip install './funcx_endpoint'
        python -m pip install safety
    - name: Run smoke tests to check liveness of hosted services
      run: |
        pytest -v funcx_endpoint/tests/smoke_tests --api-client-id ${{ secrets.API_CLIENT_ID }} --api-client-secret ${{ secrets.API_CLIENT_SECRET }}

  notify:
    runs-on: ubuntu-latest
    needs: [smoke-test]
    if: failure()
    steps:
      # FIXME: make this send to a listhost or Slack
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ github.repository }} - Hourly smoke test failed
          to: ryan.chard@gmail.com,rchard@anl.gov,chard@uchicago.edu,yadudoc1729@gmail.com,josh@globus.org,bengal1@illinois.edu,benc@hawaga.org.uk,sirosen@globus.org,uriel@globus.org
          from: funcX Tests # <user@example.com>
          body: The hourly ${{ github.repository }} workflow failed!
