name: smoke_test

on:
  push:
    paths:
      - 'funcx_endpoint/tests/smoke_tests/**'
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    paths:
      - 'funcx_endpoint/tests/smoke_tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies for funcx-sdk and test requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install ./funcx_sdk
        python -m pip install -r funcx_sdk/test-requirements.txt
    - name: Test sdk by just importing
      run: |
        python -c "from funcx.sdk.client import FuncXClient"
    - name: Run smoke tests to check liveness of hosted services
      run: |
        pytest -v funcx_endpoint/tests/smoke_tests --api-client-id ${{ secrets.API_CLIENT_ID }} --api-client-secret ${{ secrets.API_CLIENT_SECRET }}
